spring:
  application:
    name: 'MSOFT Minibank Service'

  datasource:
    url: jdbc:h2:mem:test-db
    driverClassName: org.h2.Driver
    username: sa
    password: posgrados
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    defer-datasource-initialization: true
